export * as commentController from './commentController.js'
export * as friendshipController from './friendshipController.js'
export * as likeController from './likeController.js'
export * as postController from './postController.js'
export * as userController from './userController.js'
